server:
  port: 8080
marketplace:
  services:
    order:
      id: http://localhost:8083
      api:
        url: /v1/order/
    product:
      id: http://product-service:8081
      api:
        url: /v1/products/
        
security:
  ignored: /favicon.ico
  basic:
    enabled: false
  user:
    name: admin
    password: admin
  oauth2:
    client:
      client-id: adminclient
      client-secret: adminsecret
      scope: read,write
      auto-approve-scopes: '.*'
      access-token-uri: http://auth-server:9999/oauth/token
      user-authorization-uri: http://auth-server:9999/oauth/authorize
      grant_type: authorization_code
    resource:
      user-info-uri: http://auth-server:9999/me
---
#confirm ROUTES
spring:
  profiles: cloud
marketplace:
  services:
    order:
      id: https://cdp-order-service-cfapps.io
    product:
      id: https://cdp-order-service-cfapps.io