server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:product
  rabbitmq:
    host: 192.168.99.100
    port: 5672
flyway:
  clean-on-validation-error: true


  
security:
  oauth2:
    client:
      client-id: adminclient
      client-secret: adminsecret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/me
---
spring:
  profiles: dev-postgres
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/product_service_dataservice
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

server:
  port: 8082
---
spring:
  profiles: cloud