server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:product

---

spring:
  profiles: dev-postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service
    username: lshannon
    password: 
flyway:
  clean-on-validation-error: true

---
spring:
  profiles: cloud